# Flutter & Dart wrapper keep rules
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# ML Kit Latin text recognition (used on Android for Yellow Form OCR)
-keep class com.google.mlkit.vision.text.** { *; }

# ML Kit optional language scripts — NOT used (only Latin/English is needed).
# R8 warns about these because google_mlkit_text_recognition references them
# via reflection, but they are not bundled in the Latin-only AAR.
# These dontwarn rules are auto-generated by Android Gradle (missing_rules.txt).
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
